name: brain_snack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8

  # 🔥 Aggiunta corretta: SharedPreferences
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Per generare icone dell'app
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/imm.png"
  adaptive_icon_background: "#1A0B2E"
  adaptive_icon_foreground: "assets/images/imm.png"
  web:
    generate: true
    image_path: "assets/images/imm.png"
    background_color: "#1A0B2E"
    theme_color: "#1A0B2E"
